#  _____                       _____                        _____ _____ 
#  / ____|                     / ____|                 /\   |  __ \_   _|
# | |  __  __ _ _ __ ___   ___| |     ___  _ __ ___   /  \  | |__) || |  
# | | |_ |/ _` | '_ ` _ \ / _ \ |    / _ \| '__/ _ \ / /\ \ |  ___/ | |  
# | |__| | (_| | | | | | |  __/ |___| (_) | | |  __// ____ \| |    _| |_ 
#  \_____|\__,_|_| |_| |_|\___|\_____\___/|_|  \___/_/    \_\_|   |_____|
                                                                        

#GameCoreAPI配置